// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// =============================================================================
//
// Generated by: scripts/generate-zod.ts
// Source: crates/openflow-contracts/src/**/*.rs
// Generated at: 2026-01-02T06:27:35.136Z
//
// This file contains Zod validation schemas auto-generated from Rust contract
// types. Validation rules are extracted from @validate: annotations in doc
// comments and converted to equivalent Zod constraints.
//
// To regenerate: pnpm generate:zod
//
// @see CLAUDE.md - Type Generation Flow section
// =============================================================================

import { z } from 'zod';

// =============================================================================
// Enum Schemas
// =============================================================================

/**
 * Zod schema for ChatRole enum
 * @generated from entities/chat.rs
 */
export const chatRoleSchema = z.enum(['main', 'review', 'test', 'terminal']);

/**
 * Zod schema for CliToolType enum
 * @generated from entities/executor.rs
 */
export const cliToolTypeSchema = z.enum(['claudecode', 'geminicli', 'codexcli', 'cursorcli', 'amazonqcli', 'copilotcli', 'custom']);

/**
 * Zod schema for DataAction enum
 * @generated from events/mod.rs
 */
export const dataActionSchema = z.enum(['created', 'updated', 'deleted']);

/**
 * Zod schema for EntityType enum
 * @generated from events/mod.rs
 */
export const entityTypeSchema = z.enum(['project', 'task', 'chat', 'message', 'executorprofile', 'process', 'setting', 'workflowtemplate', 'worktree']);

/**
 * Zod schema for Event enum
 * @generated from events/mod.rs
 */
export const eventSchema = z.enum(['datachanged', 'processoutput', 'processstatus']);

/**
 * Zod schema for FileChangeType enum
 * @generated from entities/git.rs
 */
export const fileChangeTypeSchema = z.enum(['added', 'modified', 'deleted', 'renamed', 'binary']);

/**
 * Zod schema for GitFileStatus enum
 * @generated from entities/git.rs
 */
export const gitFileStatusSchema = z.enum(['untracked', 'modified', 'staged', 'partiallystaged', 'deleted', 'renamed', 'copied', 'conflicted']);

/**
 * Zod schema for MessageRole enum
 * @generated from entities/message.rs
 */
export const messageRoleSchema = z.enum(['user', 'assistant', 'system']);

/**
 * Zod schema for OutputType enum
 * @generated from entities/process.rs
 */
export const outputTypeSchema = z.enum(['stdout', 'stderr']);

/**
 * Zod schema for ProcessStatus enum
 * @generated from entities/process.rs
 */
export const processStatusSchema = z.enum(['running', 'completed', 'failed', 'killed']);

/**
 * Zod schema for RunReason enum
 * @generated from entities/process.rs
 */
export const runReasonSchema = z.enum(['setupscript', 'cleanupscript', 'codingagent', 'devserver', 'terminal', 'verification']);

/**
 * Zod schema for TaskStatus enum
 * @generated from entities/task.rs
 */
export const taskStatusSchema = z.enum(['todo', 'inprogress', 'inreview', 'done', 'cancelled']);

/**
 * Zod schema for WorkflowStepStatus enum
 * @generated from entities/workflow.rs
 */
export const workflowStepStatusSchema = z.enum(['pending', 'inprogress', 'completed', 'skipped']);

/**
 * Zod schema for WorkflowVariable enum
 * @generated from entities/workflow.rs
 */
export const workflowVariableSchema = z.enum(['artifactspath', 'projectroot', 'worktreepath', 'taskid', 'tasktitle', 'projectname']);

/**
 * Zod schema for WorktreeStatus enum
 * @generated from entities/git.rs
 */
export const worktreeStatusSchema = z.enum(['active', 'pruned', 'locked']);

/**
 * Zod schema for WsClientMessage enum
 * @generated from events/mod.rs
 */
export const wsClientMessageSchema = z.enum(['subscribe', 'channel']);

/**
 * Zod schema for WsServerMessage enum
 * @generated from events/mod.rs
 */
export const wsServerMessageSchema = z.enum(['connected', 'client_id']);

// =============================================================================
// Request Schemas
// =============================================================================

/**
 * Zod schema for AppendMessageContentRequest
 * @request
 * @generated from requests/message.rs
 */
export const appendMessageContentRequestSchema = z.object({
  content: z.string(),
});

/**
 * Zod schema for ApplyWorkflowToTaskRequest
 * @request
 * @generated from requests/workflow.rs
 */
export const applyWorkflowToTaskRequestSchema = z.object({
  taskId: z.string(),
  templateId: z.string(),
});

/**
 * Zod schema for CreateChatRequest
 * @request
 * @generated from requests/chat.rs
 */
export const createChatRequestSchema = z.object({
  taskId: z.string().optional().nullable(),
  projectId: z.string(),
  title: z.string().optional().nullable(),
  chatRole: chatRoleSchema.optional().nullable(),
  executorProfileId: z.string().optional().nullable(),
  baseBranch: z.string().optional().nullable(),
  initialPrompt: z.string().optional().nullable(),
  hiddenPrompt: z.string().optional().nullable(),
  isPlanContainer: z.boolean().optional().nullable(),
  mainChatId: z.string().optional().nullable(),
  workflowStepIndex: z.number().int().optional().nullable(),
});

/**
 * Zod schema for CreateExecutorProfileRequest
 * @request
 * @generated from requests/executor.rs
 */
export const createExecutorProfileRequestSchema = z.object({
  name: z.string(),
  description: z.string().optional().nullable(),
  command: z.string(),
  args: z.string().optional().nullable(),
  env: z.string().optional().nullable(),
  model: z.string().optional().nullable(),
  isDefault: z.boolean().optional().nullable(),
});

/**
 * Zod schema for CreateMessageRequest
 * @request
 * @generated from requests/message.rs
 */
export const createMessageRequestSchema = z.object({
  chatId: z.string(),
  role: messageRoleSchema,
  content: z.string(),
  toolCalls: z.string().optional().nullable(),
  toolResults: z.string().optional().nullable(),
  model: z.string().optional().nullable(),
  isStreaming: z.boolean().optional().nullable(),
});

/**
 * Zod schema for CreateProcessRequest
 * @request
 * @generated from requests/process.rs
 */
export const createProcessRequestSchema = z.object({
  chatId: z.string(),
  executorProfileId: z.string().optional().nullable(),
  executorAction: z.string(),
  runReason: runReasonSchema,
  beforeHeadCommit: z.string().optional().nullable(),
});

/**
 * Zod schema for CreateProjectRequest
 * @request
 * @generated from requests/project.rs
 */
export const createProjectRequestSchema = z.object({
  name: z.string(),
  gitRepoPath: z.string(),
  baseBranch: z.string().optional().nullable(),
  setupScript: z.string().optional().nullable(),
  devScript: z.string().optional().nullable(),
  cleanupScript: z.string().optional().nullable(),
  copyFiles: z.string().optional().nullable(),
  icon: z.string().optional().nullable(),
  ruleFolders: z.string().optional().nullable(),
  alwaysIncludedRules: z.string().optional().nullable(),
  workflowsFolder: z.string().optional().nullable(),
  verificationConfig: z.string().optional().nullable(),
});

/**
 * Zod schema for CreatePullRequestRequest
 * @request
 * @generated from requests/git.rs
 */
export const createPullRequestRequestSchema = z.object({
  taskId: z.string(),
  title: z.string().optional().nullable(),
  body: z.string().optional().nullable(),
  base: z.string().optional().nullable(),
  draft: z.boolean(),
});

/**
 * Zod schema for CreateTaskRequest
 * @request
 * @generated from requests/task.rs
 */
export const createTaskRequestSchema = z.object({
  projectId: z.string(),
  title: z.string(),
  description: z.string().optional().nullable(),
  workflowTemplate: z.string().optional().nullable(),
  parentTaskId: z.string().optional().nullable(),
  baseBranch: z.string().optional().nullable(),
});

/**
 * Zod schema for CreateWorkflowTemplateRequest
 * @request
 * @generated from requests/workflow.rs
 */
export const createWorkflowTemplateRequestSchema = z.object({
  name: z.string(),
  description: z.string().optional().nullable(),
  content: z.string(),
  projectId: z.string().optional().nullable(),
});

/**
 * Zod schema for CreateWorktreeRequest
 * @request
 * @generated from requests/git.rs
 */
export const createWorktreeRequestSchema = z.object({
  repoPath: z.string(),
  branchName: z.string(),
  baseBranch: z.string(),
  worktreePath: z.string(),
});

/**
 * Zod schema for DeleteWorkflowTemplateRequest
 * @request
 * @generated from requests/workflow.rs
 */
export const deleteWorkflowTemplateRequestSchema = z.object({
  id: z.string(),
});

/**
 * Zod schema for DeleteWorktreeRequest
 * @request
 * @generated from requests/git.rs
 */
export const deleteWorktreeRequestSchema = z.object({
  repoPath: z.string(),
  worktreePath: z.string(),
  force: z.boolean(),
});

/**
 * Zod schema for GenerateBranchNameRequest
 * @request
 * @generated from requests/git.rs
 */
export const generateBranchNameRequestSchema = z.object({
  taskId: z.string(),
  chatRole: z.string(),
});

/**
 * Zod schema for GenerateWorktreePathRequest
 * @request
 * @generated from requests/git.rs
 */
export const generateWorktreePathRequestSchema = z.object({
  basePath: z.string(),
  projectId: z.string(),
  taskId: z.string(),
  chatRole: z.string(),
});

/**
 * Zod schema for GetCommitsRequest
 * @request
 * @generated from requests/git.rs
 */
export const getCommitsRequestSchema = z.object({
  worktreePath: z.string(),
  limit: z.number().int().optional().nullable(),
  skip: z.number().int().optional().nullable(),
  refName: z.string().optional().nullable(),
});

/**
 * Zod schema for GetCurrentBranchRequest
 * @request
 * @generated from requests/git.rs
 */
export const getCurrentBranchRequestSchema = z.object({
  worktreePath: z.string(),
});

/**
 * Zod schema for GetDiffRequest
 * @request
 * @generated from requests/git.rs
 */
export const getDiffRequestSchema = z.object({
  worktreePath: z.string(),
  staged: z.boolean(),
  paths: z.array(z.string()).optional().nullable(),
});

/**
 * Zod schema for GetHeadCommitRequest
 * @request
 * @generated from requests/git.rs
 */
export const getHeadCommitRequestSchema = z.object({
  worktreePath: z.string(),
});

/**
 * Zod schema for GetTaskCommitsRequest
 * @request
 * @generated from requests/git.rs
 */
export const getTaskCommitsRequestSchema = z.object({
  taskId: z.string(),
  limit: z.number().int().optional().nullable(),
});

/**
 * Zod schema for GetTaskDiffRequest
 * @request
 * @generated from requests/git.rs
 */
export const getTaskDiffRequestSchema = z.object({
  taskId: z.string(),
});

/**
 * Zod schema for GetWorkflowTemplateRequest
 * @request
 * @generated from requests/workflow.rs
 */
export const getWorkflowTemplateRequestSchema = z.object({
  id: z.string(),
  projectId: z.string().optional().nullable(),
});

/**
 * Zod schema for HasUncommittedChangesRequest
 * @request
 * @generated from requests/git.rs
 */
export const hasUncommittedChangesRequestSchema = z.object({
  worktreePath: z.string(),
});

/**
 * Zod schema for KillProcessRequest
 * @request
 * @generated from requests/process.rs
 */
export const killProcessRequestSchema = z.object({
  signal: z.string().optional().nullable(),
});

/**
 * Zod schema for ListProcessesRequest
 * @request
 * @generated from requests/process.rs
 */
export const listProcessesRequestSchema = z.object({
  chatId: z.string().optional().nullable(),
  status: processStatusSchema.optional().nullable(),
  runReason: runReasonSchema.optional().nullable(),
  runningOnly: z.boolean().optional().nullable(),
  limit: z.number().int().optional().nullable(),
});

/**
 * Zod schema for ListWorkflowTemplatesRequest
 * @request
 * @generated from requests/workflow.rs
 */
export const listWorkflowTemplatesRequestSchema = z.object({
  includeBuiltin: z.boolean().optional().nullable(),
  projectId: z.string().optional().nullable(),
});

/**
 * Zod schema for ListWorktreesRequest
 * @request
 * @generated from requests/git.rs
 */
export const listWorktreesRequestSchema = z.object({
  repoPath: z.string(),
});

/**
 * Zod schema for ParseWorkflowRequest
 * @request
 * @generated from requests/workflow.rs
 */
export const parseWorkflowRequestSchema = z.object({
  content: z.string(),
});

/**
 * Zod schema for PushBranchRequest
 * @request
 * @generated from requests/git.rs
 */
export const pushBranchRequestSchema = z.object({
  worktreePath: z.string(),
  remote: z.string().optional().nullable(),
  force: z.boolean(),
  setUpstream: z.boolean(),
});

/**
 * Zod schema for ResizeProcessRequest
 * @request
 * @generated from requests/process.rs
 */
export const resizeProcessRequestSchema = z.object({
  cols: z.number().int().nonnegative(),
  rows: z.number().int().nonnegative(),
});

/**
 * Zod schema for RunExecutorRequest
 * @request
 * @generated from requests/executor.rs
 */
export const runExecutorRequestSchema = z.object({
  chatId: z.string(),
  prompt: z.string(),
  executorProfileId: z.string().optional().nullable(),
});

/**
 * Zod schema for SendProcessInputRequest
 * @request
 * @generated from requests/process.rs
 */
export const sendProcessInputRequestSchema = z.object({
  input: z.string(),
});

/**
 * Zod schema for SetDefaultExecutorProfileRequest
 * @request
 * @generated from requests/executor.rs
 */
export const setDefaultExecutorProfileRequestSchema = z.object({
  id: z.string(),
});

/**
 * Zod schema for SetMessageStreamingRequest
 * @request
 * @generated from requests/message.rs
 */
export const setMessageStreamingRequestSchema = z.object({
  isStreaming: z.boolean(),
});

/**
 * Zod schema for SubstituteWorkflowVariablesRequest
 * @request
 * @generated from requests/workflow.rs
 */
export const substituteWorkflowVariablesRequestSchema = z.object({
  content: z.string(),
  taskId: z.string().optional().nullable(),
  chatId: z.string().optional().nullable(),
  customVariables: z.string() /* std::collections::HashMap<String, String> */.optional().nullable(),
});

/**
 * Zod schema for UpdateChatRequest
 * @request
 * @generated from requests/chat.rs
 */
export const updateChatRequestSchema = z.object({
  title: z.string().optional().nullable(),
  executorProfileId: z.string().optional().nullable(),
  branch: z.string().optional().nullable(),
  worktreePath: z.string().optional().nullable(),
  worktreeDeleted: z.boolean().optional().nullable(),
  setupCompletedAt: z.string().optional().nullable(),
  initialPrompt: z.string().optional().nullable(),
  hiddenPrompt: z.string().optional().nullable(),
  claudeSessionId: z.string().optional().nullable(),
});

/**
 * Zod schema for UpdateExecutorProfileRequest
 * @request
 * @generated from requests/executor.rs
 */
export const updateExecutorProfileRequestSchema = z.object({
  name: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  command: z.string().optional().nullable(),
  args: z.string().optional().nullable(),
  env: z.string().optional().nullable(),
  model: z.string().optional().nullable(),
  isDefault: z.boolean().optional().nullable(),
});

/**
 * Zod schema for UpdateMessageRequest
 * @request
 * @generated from requests/message.rs
 */
export const updateMessageRequestSchema = z.object({
  content: z.string().optional().nullable(),
  toolCalls: z.string().optional().nullable(),
  toolResults: z.string().optional().nullable(),
  isStreaming: z.boolean().optional().nullable(),
  tokensUsed: z.number().int().optional().nullable(),
  model: z.string().optional().nullable(),
});

/**
 * Zod schema for UpdateProcessRequest
 * @request
 * @generated from requests/process.rs
 */
export const updateProcessRequestSchema = z.object({
  status: processStatusSchema.optional().nullable(),
  exitCode: z.number().int().optional().nullable(),
  afterHeadCommit: z.string().optional().nullable(),
  pid: z.number().int().optional().nullable(),
  completedAt: z.string().optional().nullable(),
});

/**
 * Zod schema for UpdateProjectRequest
 * @request
 * @generated from requests/project.rs
 */
export const updateProjectRequestSchema = z.object({
  name: z.string().optional().nullable(),
  gitRepoPath: z.string().optional().nullable(),
  baseBranch: z.string().optional().nullable(),
  setupScript: z.string().optional().nullable(),
  devScript: z.string().optional().nullable(),
  cleanupScript: z.string().optional().nullable(),
  copyFiles: z.string().optional().nullable(),
  icon: z.string().optional().nullable(),
  ruleFolders: z.string().optional().nullable(),
  alwaysIncludedRules: z.string().optional().nullable(),
  workflowsFolder: z.string().optional().nullable(),
  verificationConfig: z.string().optional().nullable(),
});

/**
 * Zod schema for UpdateTaskRequest
 * @request
 * @generated from requests/task.rs
 */
export const updateTaskRequestSchema = z.object({
  title: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  status: taskStatusSchema.optional().nullable(),
  autoStartNextStep: z.boolean().optional().nullable(),
  defaultExecutorProfileId: z.string().optional().nullable(),
});

/**
 * Zod schema for UpdateWorkflowStepRequest
 * @request
 * @generated from requests/workflow.rs
 */
export const updateWorkflowStepRequestSchema = z.object({
  taskId: z.string(),
  stepIndex: z.number().int(),
  status: workflowStepStatusSchema.optional().nullable(),
  chatId: z.string().optional().nullable(),
});

/**
 * Zod schema for UpdateWorkflowTemplateRequest
 * @request
 * @generated from requests/workflow.rs
 */
export const updateWorkflowTemplateRequestSchema = z.object({
  name: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  content: z.string().optional().nullable(),
});

// =============================================================================
// Other Schemas
// =============================================================================

/**
 * Zod schema for Branch
 * @generated from entities/git.rs
 */
export const branchSchema = z.object({
  name: z.string(),
  isCurrent: z.boolean(),
  isRemote: z.boolean(),
  upstream: z.string().optional().nullable(),
  headCommit: z.string().optional().nullable(),
});

/**
 * Zod schema for Chat
 * @generated from entities/chat.rs
 */
export const chatSchema = z.object({
  id: z.string(),
  taskId: z.string().optional().nullable(),
  projectId: z.string(),
  title: z.string().optional().nullable(),
  chatRole: chatRoleSchema,
  executorProfileId: z.string().optional().nullable(),
  baseBranch: z.string(),
  branch: z.string().optional().nullable(),
  worktreePath: z.string().optional().nullable(),
  worktreeDeleted: z.boolean(),
  setupCompletedAt: z.string().optional().nullable(),
  initialPrompt: z.string().optional().nullable(),
  hiddenPrompt: z.string().optional().nullable(),
  isPlanContainer: z.boolean(),
  mainChatId: z.string().optional().nullable(),
  workflowStepIndex: z.number().int().optional().nullable(),
  claudeSessionId: z.string().optional().nullable(),
  archivedAt: z.string().optional().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * Zod schema for ChatSummary
 * @generated from entities/chat.rs
 */
export const chatSummarySchema = z.object({
  id: z.string(),
  taskId: z.string().optional().nullable(),
  projectId: z.string(),
  title: z.string().optional().nullable(),
  chatRole: chatRoleSchema,
  hasWorktree: z.boolean(),
  isSetupCompleted: z.boolean(),
  isArchived: z.boolean(),
  updatedAt: z.string(),
});

/**
 * Zod schema for ChatWithMessageCount
 * @generated from entities/chat.rs
 */
export const chatWithMessageCountSchema = z.object({
  chat: z.string() /* Chat */,
  messageCount: z.number().int(),
});

/**
 * Zod schema for Commit
 * @generated from entities/git.rs
 */
export const commitSchema = z.object({
  hash: z.string(),
  shortHash: z.string(),
  message: z.string(),
  author: z.string(),
  authorEmail: z.string(),
  date: z.string(),
  filesChanged: z.number().int(),
  additions: z.number().int(),
  deletions: z.number().int(),
});

/**
 * Zod schema for CommitSummary
 * @generated from entities/git.rs
 */
export const commitSummarySchema = z.object({
  shortHash: z.string(),
  message: z.string(),
  author: z.string(),
  date: z.string(),
});

/**
 * Zod schema for DataChangedEvent
 * @generated from events/mod.rs
 */
export const dataChangedEventSchema = z.object({
  entity: entityTypeSchema,
  action: dataActionSchema,
  id: z.string(),
  data: z.unknown().optional().nullable(),
  timestamp: z.string().optional().nullable(),
  parentId: z.string().optional().nullable(),
});

/**
 * Zod schema for DiffHunk
 * @generated from entities/git.rs
 */
export const diffHunkSchema = z.object({
  oldStart: z.number().int(),
  oldLines: z.number().int(),
  newStart: z.number().int(),
  newLines: z.number().int(),
  content: z.string(),
});

/**
 * Zod schema for ExecutionProcess
 * @generated from entities/process.rs
 */
export const executionProcessSchema = z.object({
  id: z.string(),
  chatId: z.string(),
  executorProfileId: z.string().optional().nullable(),
  status: processStatusSchema,
  exitCode: z.number().int().optional().nullable(),
  executorAction: z.string(),
  runReason: runReasonSchema,
  beforeHeadCommit: z.string().optional().nullable(),
  afterHeadCommit: z.string().optional().nullable(),
  pid: z.number().int().optional().nullable(),
  startedAt: z.string(),
  completedAt: z.string().optional().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * Zod schema for ExecutorProfile
 * @generated from entities/executor.rs
 */
export const executorProfileSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional().nullable(),
  command: z.string(),
  args: z.string().optional().nullable(),
  env: z.string().optional().nullable(),
  model: z.string().optional().nullable(),
  isDefault: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * Zod schema for ExecutorProfileSummary
 * @generated from entities/executor.rs
 */
export const executorProfileSummarySchema = z.object({
  id: z.string(),
  name: z.string(),
  command: z.string(),
  model: z.string().optional().nullable(),
  isDefault: z.boolean(),
});

/**
 * Zod schema for FileDiff
 * @generated from entities/git.rs
 */
export const fileDiffSchema = z.object({
  path: z.string(),
  oldPath: z.string().optional().nullable(),
  hunks: z.array(z.string()),
  additions: z.number().int(),
  deletions: z.number().int(),
  isBinary: z.boolean(),
  isNew: z.boolean(),
  isDeleted: z.boolean(),
  isRenamed: z.boolean(),
});

/**
 * Zod schema for FileDiffSummary
 * @generated from entities/git.rs
 */
export const fileDiffSummarySchema = z.object({
  path: z.string(),
  additions: z.number().int(),
  deletions: z.number().int(),
  changeType: fileChangeTypeSchema,
});

/**
 * Zod schema for GitStatus
 * @generated from entities/git.rs
 */
export const gitStatusSchema = z.object({
  branch: z.string(),
  hasChanges: z.boolean(),
  ahead: z.number().int(),
  behind: z.number().int(),
  files: z.array(z.string()),
});

/**
 * Zod schema for GitStatusFile
 * @generated from entities/git.rs
 */
export const gitStatusFileSchema = z.object({
  path: z.string(),
  status: gitFileStatusSchema,
  originalPath: z.string().optional().nullable(),
});

/**
 * Zod schema for Message
 * @generated from entities/message.rs
 */
export const messageSchema = z.object({
  id: z.string(),
  chatId: z.string(),
  role: messageRoleSchema,
  content: z.string(),
  toolCalls: z.string().optional().nullable(),
  toolResults: z.string().optional().nullable(),
  isStreaming: z.boolean(),
  tokensUsed: z.number().int().optional().nullable(),
  model: z.string().optional().nullable(),
  createdAt: z.string(),
});

/**
 * Zod schema for MessageSummary
 * @generated from entities/message.rs
 */
export const messageSummarySchema = z.object({
  id: z.string(),
  chatId: z.string(),
  role: messageRoleSchema,
  contentPreview: z.string(),
  hasToolCalls: z.boolean(),
  isStreaming: z.boolean(),
  createdAt: z.string(),
});

/**
 * Zod schema for ProcessOutputEvent
 * @generated from entities/process.rs
 */
export const processOutputEventSchema = z.object({
  processId: z.string(),
  outputType: outputTypeSchema,
  content: z.string(),
  timestamp: z.string(),
});

/**
 * Zod schema for ProcessStatusEvent
 * @generated from entities/process.rs
 */
export const processStatusEventSchema = z.object({
  processId: z.string(),
  status: processStatusSchema,
  exitCode: z.number().int().optional().nullable(),
});

/**
 * Zod schema for ProcessSummary
 * @generated from entities/process.rs
 */
export const processSummarySchema = z.object({
  id: z.string(),
  chatId: z.string(),
  status: processStatusSchema,
  exitCode: z.number().int().optional().nullable(),
  executorAction: z.string(),
  runReason: runReasonSchema,
  pid: z.number().int().optional().nullable(),
  startedAt: z.string(),
  completedAt: z.string().optional().nullable(),
});

/**
 * Zod schema for Project
 * @generated from entities/project.rs
 */
export const projectSchema = z.object({
  id: z.string(),
  name: z.string(),
  gitRepoPath: z.string(),
  baseBranch: z.string(),
  setupScript: z.string(),
  devScript: z.string(),
  cleanupScript: z.string().optional().nullable(),
  copyFiles: z.string().optional().nullable(),
  icon: z.string(),
  ruleFolders: z.string().optional().nullable(),
  alwaysIncludedRules: z.string().optional().nullable(),
  workflowsFolder: z.string(),
  verificationConfig: z.string().optional().nullable(),
  archivedAt: z.string().optional().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * Zod schema for ProjectSummary
 * @generated from entities/project.rs
 */
export const projectSummarySchema = z.object({
  id: z.string(),
  name: z.string(),
  gitRepoPath: z.string(),
  icon: z.string(),
  isArchived: z.boolean(),
  updatedAt: z.string(),
});

/**
 * Zod schema for ProjectWithStats
 * @generated from entities/project.rs
 */
export const projectWithStatsSchema = z.object({
  project: z.string() /* Project */,
  activeTaskCount: z.number().int(),
  totalTaskCount: z.number().int(),
  inProgressTaskCount: z.number().int(),
  completedTaskCount: z.number().int(),
});

/**
 * Zod schema for PullRequestResult
 * @generated from entities/git.rs
 */
export const pullRequestResultSchema = z.object({
  url: z.string(),
  number: z.number().int().nonnegative(),
  branch: z.string(),
});

/**
 * Zod schema for Task
 * @generated from entities/task.rs
 */
export const taskSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  title: z.string(),
  description: z.string().optional().nullable(),
  status: taskStatusSchema,
  workflowTemplate: z.string().optional().nullable(),
  actionsRequiredCount: z.number().int(),
  parentTaskId: z.string().optional().nullable(),
  autoStartNextStep: z.boolean(),
  defaultExecutorProfileId: z.string().optional().nullable(),
  baseBranch: z.string().optional().nullable(),
  archivedAt: z.string().optional().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * Zod schema for TaskSummary
 * @generated from entities/task.rs
 */
export const taskSummarySchema = z.object({
  id: z.string(),
  projectId: z.string(),
  title: z.string(),
  status: taskStatusSchema,
  actionsRequiredCount: z.number().int(),
  parentTaskId: z.string().optional().nullable(),
  isArchived: z.boolean(),
  updatedAt: z.string(),
});

/**
 * Zod schema for TaskWithChatCount
 * @generated from entities/task.rs
 */
export const taskWithChatCountSchema = z.object({
  task: z.string() /* Task */,
  chatCount: z.number().int(),
});

/**
 * Zod schema for WorkflowContext
 * @generated from entities/workflow.rs
 */
export const workflowContextSchema = z.object({
  artifactsPath: z.string().optional().nullable(),
  projectRoot: z.string().optional().nullable(),
  worktreePath: z.string().optional().nullable(),
  taskId: z.string().optional().nullable(),
  taskTitle: z.string().optional().nullable(),
  projectName: z.string().optional().nullable(),
});

/**
 * Zod schema for WorkflowStep
 * @generated from entities/workflow.rs
 */
export const workflowStepSchema = z.object({
  index: z.number().int(),
  name: z.string(),
  description: z.string(),
  status: workflowStepStatusSchema,
  chatId: z.string().optional().nullable(),
});

/**
 * Zod schema for WorkflowTemplate
 * @generated from entities/workflow.rs
 */
export const workflowTemplateSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional().nullable(),
  content: z.string(),
  isBuiltin: z.boolean(),
  steps: z.array(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * Zod schema for WorkflowTemplateSummary
 * @generated from entities/workflow.rs
 */
export const workflowTemplateSummarySchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional().nullable(),
  isBuiltin: z.boolean(),
  stepCount: z.number().int(),
});

/**
 * Zod schema for Worktree
 * @generated from entities/git.rs
 */
export const worktreeSchema = z.object({
  path: z.string(),
  branch: z.string(),
  headCommit: z.string().optional().nullable(),
  isMain: z.boolean(),
  status: worktreeStatusSchema,
});

/**
 * Zod schema for WorktreeSummary
 * @generated from entities/git.rs
 */
export const worktreeSummarySchema = z.object({
  path: z.string(),
  branch: z.string(),
  isMain: z.boolean(),
});

// =============================================================================
// Type Exports (inferred from schemas)
// =============================================================================

export type ChatRoleGenerated = z.infer<typeof chatRoleSchema>;
export type CliToolTypeGenerated = z.infer<typeof cliToolTypeSchema>;
export type DataActionGenerated = z.infer<typeof dataActionSchema>;
export type EntityTypeGenerated = z.infer<typeof entityTypeSchema>;
export type EventGenerated = z.infer<typeof eventSchema>;
export type FileChangeTypeGenerated = z.infer<typeof fileChangeTypeSchema>;
export type GitFileStatusGenerated = z.infer<typeof gitFileStatusSchema>;
export type MessageRoleGenerated = z.infer<typeof messageRoleSchema>;
export type OutputTypeGenerated = z.infer<typeof outputTypeSchema>;
export type ProcessStatusGenerated = z.infer<typeof processStatusSchema>;
export type RunReasonGenerated = z.infer<typeof runReasonSchema>;
export type TaskStatusGenerated = z.infer<typeof taskStatusSchema>;
export type WorkflowStepStatusGenerated = z.infer<typeof workflowStepStatusSchema>;
export type WorkflowVariableGenerated = z.infer<typeof workflowVariableSchema>;
export type WorktreeStatusGenerated = z.infer<typeof worktreeStatusSchema>;
export type WsClientMessageGenerated = z.infer<typeof wsClientMessageSchema>;
export type WsServerMessageGenerated = z.infer<typeof wsServerMessageSchema>;

export type AppendMessageContentRequestGenerated = z.infer<typeof appendMessageContentRequestSchema>;
export type ApplyWorkflowToTaskRequestGenerated = z.infer<typeof applyWorkflowToTaskRequestSchema>;
export type BranchGenerated = z.infer<typeof branchSchema>;
export type ChatGenerated = z.infer<typeof chatSchema>;
export type ChatSummaryGenerated = z.infer<typeof chatSummarySchema>;
export type ChatWithMessageCountGenerated = z.infer<typeof chatWithMessageCountSchema>;
export type CommitGenerated = z.infer<typeof commitSchema>;
export type CommitSummaryGenerated = z.infer<typeof commitSummarySchema>;
export type CreateChatRequestGenerated = z.infer<typeof createChatRequestSchema>;
export type CreateExecutorProfileRequestGenerated = z.infer<typeof createExecutorProfileRequestSchema>;
export type CreateMessageRequestGenerated = z.infer<typeof createMessageRequestSchema>;
export type CreateProcessRequestGenerated = z.infer<typeof createProcessRequestSchema>;
export type CreateProjectRequestGenerated = z.infer<typeof createProjectRequestSchema>;
export type CreatePullRequestRequestGenerated = z.infer<typeof createPullRequestRequestSchema>;
export type CreateTaskRequestGenerated = z.infer<typeof createTaskRequestSchema>;
export type CreateWorkflowTemplateRequestGenerated = z.infer<typeof createWorkflowTemplateRequestSchema>;
export type CreateWorktreeRequestGenerated = z.infer<typeof createWorktreeRequestSchema>;
export type DataChangedEventGenerated = z.infer<typeof dataChangedEventSchema>;
export type DeleteWorkflowTemplateRequestGenerated = z.infer<typeof deleteWorkflowTemplateRequestSchema>;
export type DeleteWorktreeRequestGenerated = z.infer<typeof deleteWorktreeRequestSchema>;
export type DiffHunkGenerated = z.infer<typeof diffHunkSchema>;
export type ExecutionProcessGenerated = z.infer<typeof executionProcessSchema>;
export type ExecutorProfileGenerated = z.infer<typeof executorProfileSchema>;
export type ExecutorProfileSummaryGenerated = z.infer<typeof executorProfileSummarySchema>;
export type FileDiffGenerated = z.infer<typeof fileDiffSchema>;
export type FileDiffSummaryGenerated = z.infer<typeof fileDiffSummarySchema>;
export type GenerateBranchNameRequestGenerated = z.infer<typeof generateBranchNameRequestSchema>;
export type GenerateWorktreePathRequestGenerated = z.infer<typeof generateWorktreePathRequestSchema>;
export type GetCommitsRequestGenerated = z.infer<typeof getCommitsRequestSchema>;
export type GetCurrentBranchRequestGenerated = z.infer<typeof getCurrentBranchRequestSchema>;
export type GetDiffRequestGenerated = z.infer<typeof getDiffRequestSchema>;
export type GetHeadCommitRequestGenerated = z.infer<typeof getHeadCommitRequestSchema>;
export type GetTaskCommitsRequestGenerated = z.infer<typeof getTaskCommitsRequestSchema>;
export type GetTaskDiffRequestGenerated = z.infer<typeof getTaskDiffRequestSchema>;
export type GetWorkflowTemplateRequestGenerated = z.infer<typeof getWorkflowTemplateRequestSchema>;
export type GitStatusGenerated = z.infer<typeof gitStatusSchema>;
export type GitStatusFileGenerated = z.infer<typeof gitStatusFileSchema>;
export type HasUncommittedChangesRequestGenerated = z.infer<typeof hasUncommittedChangesRequestSchema>;
export type KillProcessRequestGenerated = z.infer<typeof killProcessRequestSchema>;
export type ListProcessesRequestGenerated = z.infer<typeof listProcessesRequestSchema>;
export type ListWorkflowTemplatesRequestGenerated = z.infer<typeof listWorkflowTemplatesRequestSchema>;
export type ListWorktreesRequestGenerated = z.infer<typeof listWorktreesRequestSchema>;
export type MessageGenerated = z.infer<typeof messageSchema>;
export type MessageSummaryGenerated = z.infer<typeof messageSummarySchema>;
export type ParseWorkflowRequestGenerated = z.infer<typeof parseWorkflowRequestSchema>;
export type ProcessOutputEventGenerated = z.infer<typeof processOutputEventSchema>;
export type ProcessStatusEventGenerated = z.infer<typeof processStatusEventSchema>;
export type ProcessSummaryGenerated = z.infer<typeof processSummarySchema>;
export type ProjectGenerated = z.infer<typeof projectSchema>;
export type ProjectSummaryGenerated = z.infer<typeof projectSummarySchema>;
export type ProjectWithStatsGenerated = z.infer<typeof projectWithStatsSchema>;
export type PullRequestResultGenerated = z.infer<typeof pullRequestResultSchema>;
export type PushBranchRequestGenerated = z.infer<typeof pushBranchRequestSchema>;
export type ResizeProcessRequestGenerated = z.infer<typeof resizeProcessRequestSchema>;
export type RunExecutorRequestGenerated = z.infer<typeof runExecutorRequestSchema>;
export type SendProcessInputRequestGenerated = z.infer<typeof sendProcessInputRequestSchema>;
export type SetDefaultExecutorProfileRequestGenerated = z.infer<typeof setDefaultExecutorProfileRequestSchema>;
export type SetMessageStreamingRequestGenerated = z.infer<typeof setMessageStreamingRequestSchema>;
export type SubstituteWorkflowVariablesRequestGenerated = z.infer<typeof substituteWorkflowVariablesRequestSchema>;
export type TaskGenerated = z.infer<typeof taskSchema>;
export type TaskSummaryGenerated = z.infer<typeof taskSummarySchema>;
export type TaskWithChatCountGenerated = z.infer<typeof taskWithChatCountSchema>;
export type UpdateChatRequestGenerated = z.infer<typeof updateChatRequestSchema>;
export type UpdateExecutorProfileRequestGenerated = z.infer<typeof updateExecutorProfileRequestSchema>;
export type UpdateMessageRequestGenerated = z.infer<typeof updateMessageRequestSchema>;
export type UpdateProcessRequestGenerated = z.infer<typeof updateProcessRequestSchema>;
export type UpdateProjectRequestGenerated = z.infer<typeof updateProjectRequestSchema>;
export type UpdateTaskRequestGenerated = z.infer<typeof updateTaskRequestSchema>;
export type UpdateWorkflowStepRequestGenerated = z.infer<typeof updateWorkflowStepRequestSchema>;
export type UpdateWorkflowTemplateRequestGenerated = z.infer<typeof updateWorkflowTemplateRequestSchema>;
export type WorkflowContextGenerated = z.infer<typeof workflowContextSchema>;
export type WorkflowStepGenerated = z.infer<typeof workflowStepSchema>;
export type WorkflowTemplateGenerated = z.infer<typeof workflowTemplateSchema>;
export type WorkflowTemplateSummaryGenerated = z.infer<typeof workflowTemplateSummarySchema>;
export type WorktreeGenerated = z.infer<typeof worktreeSchema>;
export type WorktreeSummaryGenerated = z.infer<typeof worktreeSummarySchema>;
