// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// =============================================================================
//
// Generated by: scripts/generate-command-map.ts
// Source: crates/openflow-contracts/src/endpoints/mod.rs
// Generated at: 2026-01-02T06:27:35.744Z
//
// This file maps Tauri IPC command names to HTTP endpoint metadata.
// Used by the HTTP transport layer when running in browser mode.
//
// The mapping enables seamless switching between:
// - Tauri IPC (desktop app with built-in backend)
// - HTTP REST API (browser connecting to standalone server)
//
// To regenerate: pnpm generate:command-map
//
// @see CLAUDE.md - Flexible Backend Architecture section
// =============================================================================

/**
 * HTTP method for REST endpoints
 */
export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';

/**
 * Metadata for mapping a Tauri command to an HTTP endpoint.
 */
export interface EndpointMapping {
  /** HTTP method for the request */
  method: HttpMethod;
  /** URL path with :param placeholders (e.g., "/api/projects/:id") */
  path: string;
  /** Names of path parameters that need substitution */
  pathParams: readonly string[];
  /** Names of query parameters to include in URL */
  queryParams: readonly string[];
  /** Whether the endpoint expects a request body */
  hasRequestBody: boolean;
  /** Response type hint for documentation */
  responseType: string;
}

/**
 * Mapping from Tauri command names to HTTP endpoint metadata.
 *
 * This map is used by the HTTP transport to convert IPC-style calls
 * to REST API requests when running in browser mode.
 *
 * @example
 * ```ts
 * const mapping = COMMAND_MAP['get_project'];
 * // { method: 'GET', path: '/api/projects/:id', pathParams: ['id'], ... }
 * ```
 */
export const COMMAND_MAP: Readonly<Record<string, EndpointMapping>> = {
  /** Append content to a message (for streaming) */
  append_message_content: {
    method: 'POST',
    path: '/api/messages/:id/append',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Message',
  },
  /** Archive a chat (soft delete) */
  archive_chat: {
    method: 'POST',
    path: '/api/chats/:id/archive',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Chat',
  },
  /** Archive a project (soft delete) */
  archive_project: {
    method: 'POST',
    path: '/api/projects/:id/archive',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Project',
  },
  /** Archive a task (soft delete) */
  archive_task: {
    method: 'POST',
    path: '/api/tasks/:id/archive',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Task',
  },
  /** Create a new chat */
  create_chat: {
    method: 'POST',
    path: '/api/chats',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Chat',
  },
  /** Create a new executor profile */
  create_executor_profile: {
    method: 'POST',
    path: '/api/executor-profiles',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'ExecutorProfile',
  },
  /** Create a new message */
  create_message: {
    method: 'POST',
    path: '/api/messages',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Message',
  },
  /** Create a new project */
  create_project: {
    method: 'POST',
    path: '/api/projects',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Project',
  },
  /** Create a GitHub pull request */
  create_pull_request: {
    method: 'POST',
    path: '/api/github/pull-requests',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'PullRequestResult',
  },
  /** Create a new task */
  create_task: {
    method: 'POST',
    path: '/api/tasks',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Task',
  },
  /** Create a new git worktree */
  create_worktree: {
    method: 'POST',
    path: '/api/git/worktrees',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Worktree',
  },
  /** Delete a chat permanently */
  delete_chat: {
    method: 'DELETE',
    path: '/api/chats/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'void',
  },
  /** Delete an executor profile */
  delete_executor_profile: {
    method: 'DELETE',
    path: '/api/executor-profiles/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'void',
  },
  /** Delete a message */
  delete_message: {
    method: 'DELETE',
    path: '/api/messages/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'void',
  },
  /** Delete a project permanently */
  delete_project: {
    method: 'DELETE',
    path: '/api/projects/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'void',
  },
  /** Delete a setting */
  delete_setting: {
    method: 'DELETE',
    path: '/api/settings/:key',
    pathParams: ['key'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'void',
  },
  /** Delete a task permanently */
  delete_task: {
    method: 'DELETE',
    path: '/api/tasks/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'void',
  },
  /** Delete a git worktree */
  delete_worktree: {
    method: 'DELETE',
    path: '/api/git/worktrees',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'void',
  },
  /** Duplicate a task */
  duplicate_task: {
    method: 'POST',
    path: '/api/tasks/:id/duplicate',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Task',
  },
  /** Get all settings */
  get_all_settings: {
    method: 'GET',
    path: '/api/settings',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Setting[]',
  },
  /** Get built-in workflow templates */
  get_builtin_workflow_templates: {
    method: 'GET',
    path: '/api/workflows/templates/builtin',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'WorkflowTemplate[]',
  },
  /** Get a chat by ID with its messages */
  get_chat: {
    method: 'GET',
    path: '/api/chats/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'ChatWithMessages',
  },
  /** Get commits for a worktree */
  get_commits: {
    method: 'GET',
    path: '/api/git/commits',
    pathParams: [] as const,
    queryParams: ['worktree_path', 'limit', 'base_ref'] as const,
    hasRequestBody: false,
    responseType: 'Commit[]',
  },
  /** Get current branch name */
  get_current_branch: {
    method: 'GET',
    path: '/api/git/branch/current',
    pathParams: [] as const,
    queryParams: ['repo_path'] as const,
    hasRequestBody: false,
    responseType: 'string',
  },
  /** Get the default executor profile */
  get_default_executor_profile: {
    method: 'GET',
    path: '/api/executor-profiles/default',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'ExecutorProfile',
  },
  /** Get git diff for a worktree */
  get_diff: {
    method: 'GET',
    path: '/api/git/diff',
    pathParams: [] as const,
    queryParams: ['worktree_path', 'base_ref'] as const,
    hasRequestBody: false,
    responseType: 'FileDiff[]',
  },
  /** Get an executor profile by ID */
  get_executor_profile: {
    method: 'GET',
    path: '/api/executor-profiles/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'ExecutorProfile',
  },
  /** Get HEAD commit hash */
  get_head_commit: {
    method: 'GET',
    path: '/api/git/head',
    pathParams: [] as const,
    queryParams: ['repo_path'] as const,
    hasRequestBody: false,
    responseType: 'string',
  },
  /** Get a message by ID */
  get_message: {
    method: 'GET',
    path: '/api/messages/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Message',
  },
  /** Get a process by ID */
  get_process: {
    method: 'GET',
    path: '/api/processes/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'ExecutionProcess',
  },
  /** Get a project by ID */
  get_project: {
    method: 'GET',
    path: '/api/projects/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Project',
  },
  /** Get a setting by key */
  get_setting: {
    method: 'GET',
    path: '/api/settings/:key',
    pathParams: ['key'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Setting',
  },
  /** Get a setting value or return default */
  get_setting_or_default: {
    method: 'GET',
    path: '/api/settings/:key/default',
    pathParams: ['key'] as const,
    queryParams: ['default_value'] as const,
    hasRequestBody: false,
    responseType: 'string',
  },
  /** Get a task by ID with its chats */
  get_task: {
    method: 'GET',
    path: '/api/tasks/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'TaskWithChats',
  },
  /** Get commits for a task's worktree */
  get_task_commits: {
    method: 'GET',
    path: '/api/git/tasks/:task_id/commits',
    pathParams: ['task_id'] as const,
    queryParams: ['limit'] as const,
    hasRequestBody: false,
    responseType: 'Commit[]',
  },
  /** Get git diff for a task's worktree */
  get_task_diff: {
    method: 'GET',
    path: '/api/git/tasks/:task_id/diff',
    pathParams: ['task_id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'FileDiff[]',
  },
  /** Get a workflow template by ID */
  get_workflow_template: {
    method: 'GET',
    path: '/api/workflows/templates/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'WorkflowTemplate',
  },
  /** Check if repository has uncommitted changes */
  has_uncommitted_changes: {
    method: 'GET',
    path: '/api/git/status/dirty',
    pathParams: [] as const,
    queryParams: ['repo_path'] as const,
    hasRequestBody: false,
    responseType: 'boolean',
  },
  /** Check if a process is running */
  is_process_running: {
    method: 'GET',
    path: '/api/processes/:id/running',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'boolean',
  },
  /** Kill a running process */
  kill_process: {
    method: 'POST',
    path: '/api/processes/:id/kill',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'void',
  },
  /** List all archived chats */
  list_archived_chats: {
    method: 'GET',
    path: '/api/chats/archived',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Chat[]',
  },
  /** List all archived projects */
  list_archived_projects: {
    method: 'GET',
    path: '/api/projects/archived',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Project[]',
  },
  /** List chats for a task */
  list_chats: {
    method: 'GET',
    path: '/api/chats',
    pathParams: [] as const,
    queryParams: ['task_id'] as const,
    hasRequestBody: false,
    responseType: 'Chat[]',
  },
  /** List all chats in a project */
  list_chats_by_project: {
    method: 'GET',
    path: '/api/projects/:project_id/chats',
    pathParams: ['project_id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Chat[]',
  },
  /** List all executor profiles */
  list_executor_profiles: {
    method: 'GET',
    path: '/api/executor-profiles',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'ExecutorProfile[]',
  },
  /** List messages for a chat */
  list_messages: {
    method: 'GET',
    path: '/api/messages',
    pathParams: [] as const,
    queryParams: ['chat_id'] as const,
    hasRequestBody: false,
    responseType: 'Message[]',
  },
  /** List processes, optionally filtered by chat */
  list_processes: {
    method: 'GET',
    path: '/api/processes',
    pathParams: [] as const,
    queryParams: ['chat_id'] as const,
    hasRequestBody: false,
    responseType: 'ExecutionProcess[]',
  },
  /** List all active projects */
  list_projects: {
    method: 'GET',
    path: '/api/projects',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Project[]',
  },
  /** List all running processes */
  list_running_processes: {
    method: 'GET',
    path: '/api/processes/running',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'ExecutionProcess[]',
  },
  /** List standalone chats (not attached to tasks) */
  list_standalone_chats: {
    method: 'GET',
    path: '/api/chats/standalone',
    pathParams: [] as const,
    queryParams: ['project_id'] as const,
    hasRequestBody: false,
    responseType: 'Chat[]',
  },
  /** List tasks, optionally filtered by project */
  list_tasks: {
    method: 'GET',
    path: '/api/tasks',
    pathParams: [] as const,
    queryParams: ['project_id', 'include_archived'] as const,
    hasRequestBody: false,
    responseType: 'Task[]',
  },
  /** List workflow templates for a project */
  list_workflow_templates: {
    method: 'GET',
    path: '/api/workflows/templates',
    pathParams: [] as const,
    queryParams: ['project_id'] as const,
    hasRequestBody: false,
    responseType: 'WorkflowTemplate[]',
  },
  /** List git worktrees for a repository */
  list_worktrees: {
    method: 'GET',
    path: '/api/git/worktrees',
    pathParams: [] as const,
    queryParams: ['repo_path'] as const,
    hasRequestBody: false,
    responseType: 'Worktree[]',
  },
  /** Open a file in the system editor */
  open_in_editor: {
    method: 'POST',
    path: '/api/system/open-editor',
    pathParams: [] as const,
    queryParams: ['path'] as const,
    hasRequestBody: false,
    responseType: 'void',
  },
  /** Parse workflow content into a template */
  parse_workflow_content: {
    method: 'POST',
    path: '/api/workflows/parse',
    pathParams: [] as const,
    queryParams: ['content'] as const,
    hasRequestBody: false,
    responseType: 'WorkflowTemplate',
  },
  /** Push a branch to remote */
  push_branch: {
    method: 'POST',
    path: '/api/git/push',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'void',
  },
  /** Resize process PTY dimensions */
  resize_process: {
    method: 'POST',
    path: '/api/processes/:id/resize',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'void',
  },
  /** Reveal a file in the system file explorer */
  reveal_in_explorer: {
    method: 'POST',
    path: '/api/system/reveal',
    pathParams: [] as const,
    queryParams: ['path'] as const,
    hasRequestBody: false,
    responseType: 'void',
  },
  /** Run an AI executor in a chat */
  run_executor: {
    method: 'POST',
    path: '/api/executor/run',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'ExecutionProcess',
  },
  /** Get count of running processes */
  running_process_count: {
    method: 'GET',
    path: '/api/processes/count/running',
    pathParams: [] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'number',
  },
  /** Search across projects, tasks, chats, and messages */
  search: {
    method: 'GET',
    path: '/api/search',
    pathParams: [] as const,
    queryParams: ['query', 'project_id'] as const,
    hasRequestBody: false,
    responseType: 'SearchResult',
  },
  /** Send input to a process stdin */
  send_process_input: {
    method: 'POST',
    path: '/api/processes/:id/input',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'void',
  },
  /** Set streaming status of a message */
  set_message_streaming: {
    method: 'PATCH',
    path: '/api/messages/:id/streaming',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Message',
  },
  /** Set token counts for a message */
  set_message_tokens: {
    method: 'PATCH',
    path: '/api/messages/:id/tokens',
    pathParams: ['id'] as const,
    queryParams: ['input_tokens', 'output_tokens'] as const,
    hasRequestBody: false,
    responseType: 'Message',
  },
  /** Set a setting value */
  set_setting: {
    method: 'PUT',
    path: '/api/settings/:key',
    pathParams: ['key'] as const,
    queryParams: ['value'] as const,
    hasRequestBody: false,
    responseType: 'Setting',
  },
  /** Check if a setting exists */
  setting_exists: {
    method: 'GET',
    path: '/api/settings/:key/exists',
    pathParams: ['key'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'boolean',
  },
  /** Spawn a new terminal session */
  spawn_terminal: {
    method: 'POST',
    path: '/api/terminal/spawn',
    pathParams: [] as const,
    queryParams: ['chat_id', 'working_dir'] as const,
    hasRequestBody: false,
    responseType: 'ExecutionProcess',
  },
  /** Start a workflow step by creating its worktree */
  start_workflow_step: {
    method: 'POST',
    path: '/api/chats/:id/start-step',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Chat',
  },
  /** Toggle completion status of a workflow step chat */
  toggle_step_complete: {
    method: 'POST',
    path: '/api/chats/:id/toggle-step',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Chat',
  },
  /** Unarchive a chat */
  unarchive_chat: {
    method: 'POST',
    path: '/api/chats/:id/unarchive',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Chat',
  },
  /** Unarchive a project */
  unarchive_project: {
    method: 'POST',
    path: '/api/projects/:id/unarchive',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Project',
  },
  /** Unarchive a task */
  unarchive_task: {
    method: 'POST',
    path: '/api/tasks/:id/unarchive',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: false,
    responseType: 'Task',
  },
  /** Update an existing chat */
  update_chat: {
    method: 'PATCH',
    path: '/api/chats/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Chat',
  },
  /** Update an executor profile */
  update_executor_profile: {
    method: 'PATCH',
    path: '/api/executor-profiles/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'ExecutorProfile',
  },
  /** Update an existing project */
  update_project: {
    method: 'PATCH',
    path: '/api/projects/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Project',
  },
  /** Update an existing task */
  update_task: {
    method: 'PATCH',
    path: '/api/tasks/:id',
    pathParams: ['id'] as const,
    queryParams: [] as const,
    hasRequestBody: true,
    responseType: 'Task',
  },
} as const;

/**
 * Union type of all valid command names.
 */
export type CommandName = keyof typeof COMMAND_MAP;

/**
 * Get the endpoint mapping for a command.
 *
 * @param command - Tauri command name
 * @returns The endpoint mapping or undefined if not found
 */
export function getMapping(command: string): EndpointMapping | undefined {
  return COMMAND_MAP[command as CommandName];
}

/**
 * Check if a command is known and has a mapping.
 *
 * @param command - Tauri command name
 * @returns True if the command has a mapping
 */
export function isKnownCommand(command: string): command is CommandName {
  return command in COMMAND_MAP;
}

/**
 * Build the full URL path with parameter substitution.
 *
 * Substitutes path parameters (e.g., :id) with values from args,
 * and appends query parameters as a query string.
 *
 * @param command - Tauri command name
 * @param args - Arguments containing parameter values
 * @returns The fully resolved URL path
 * @throws Error if command is unknown
 *
 * @example
 * ```ts
 * buildPath('get_project', { id: 'abc123' })
 * // Returns: '/api/projects/abc123'
 *
 * buildPath('list_tasks', { project_id: 'proj1', include_archived: 'true' })
 * // Returns: '/api/tasks?project_id=proj1&include_archived=true'
 * ```
 */
export function buildPath(command: string, args: Record<string, unknown> = {}): string {
  const mapping = getMapping(command);
  if (!mapping) {
    throw new Error(`Unknown command: ${command}. Ensure it's defined in openflow-contracts.`);
  }

  let path = mapping.path;

  // Substitute path parameters
  for (const param of mapping.pathParams) {
    const value = args[param];
    if (value !== undefined && value !== null) {
      path = path.replace(`:${param}`, encodeURIComponent(String(value)));
    } else {
      console.warn(`Missing path parameter '${param}' for command '${command}'`);
    }
  }

  // Build query string from query parameters
  const queryParts: string[] = [];
  for (const param of mapping.queryParams) {
    const value = args[param];
    if (value !== undefined && value !== null) {
      queryParts.push(`${encodeURIComponent(param)}=${encodeURIComponent(String(value))}`);
    }
  }

  if (queryParts.length > 0) {
    path += `?${queryParts.join('&')}`;
  }

  return path;
}

/**
 * Extract the request body from arguments.
 *
 * For endpoints with request bodies, this extracts the body payload
 * by looking for a 'request' field or by excluding path/query params.
 *
 * @param command - Tauri command name
 * @param args - All command arguments
 * @returns The request body object or undefined
 *
 * @example
 * ```ts
 * // With explicit request field
 * getRequestBody('create_project', { request: { name: 'My Project' } })
 * // Returns: { name: 'My Project' }
 *
 * // Without request field
 * getRequestBody('update_project', { id: 'abc', name: 'Updated' })
 * // Returns: { name: 'Updated' } (id is excluded as a path param)
 * ```
 */
export function getRequestBody(
  command: string,
  args: Record<string, unknown> = {}
): unknown | undefined {
  const mapping = getMapping(command);
  if (!mapping || !mapping.hasRequestBody) {
    return undefined;
  }

  // Check for explicit 'request' field first
  if ('request' in args && args.request !== undefined) {
    return args.request;
  }

  // Otherwise, return args minus path/query params
  const excludeKeys = new Set<string>([...mapping.pathParams, ...mapping.queryParams]);

  const body: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(args)) {
    if (!excludeKeys.has(key) && value !== undefined) {
      body[key] = value;
    }
  }

  return Object.keys(body).length > 0 ? body : undefined;
}

// =============================================================================
// Statistics
// =============================================================================
// Total commands: 76
// - DELETE: 7
// - GET: 36
// - PATCH: 6
// - POST: 26
// - PUT: 1
// =============================================================================
