/**
 * Application Entry Point
 *
 * Sets up TanStack Router with QueryClient and renders the application.
 * The router tree is auto-generated by TanStack Router from the routes/ directory.
 */

import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient } from '@tanstack/react-query';
import { RouterProvider, createRouter } from '@tanstack/react-router';

import { routeTree } from './routeTree.gen';
import type { RouterContext } from './routerContext';

import './styles/globals.css';

// Create a QueryClient instance for TanStack Query
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // Stale time: 30 seconds before refetching
      staleTime: 30 * 1000,
      // Retry failed queries once
      retry: 1,
    },
  },
});

// Create the router context
const routerContext: RouterContext = {
  queryClient,
};

// Create the router instance
const router = createRouter({
  routeTree,
  context: routerContext,
  defaultPreload: 'intent',
});

// Register the router for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById('root');

if (!rootElement) {
  throw new Error('Root element not found');
}

createRoot(rootElement).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>
);
